### ISSUE TITLE
No build info/procedure available

### ISSUE THREAD

**Issue by elacunza** [VirtualCable/uds-actor#2]
Hello,

Thanks a lot for your open source effort.

Currently there is no build info, I think releasing info on how to build windows/linux/macosx actor binaries from this repository is necessary if you expect others to play and contribute back.

Also, releasing binaries could help OpenUDS community.

Thanks

**Comment by dkmstr** [comment]
There is a folder with "linux" and a makefile there, even an script... :)
For Windows, is just using or source form or pyinstaller, i'll add anyway a procedure to build binaries for windows.

Sorry for the delay, didn't noticed the issue :(

**Comment by elacunza** [comment]
Yes, sorry about Linux buids; I was looking for building Windows actors, yes. Will take a look to pyinstaller, thanks!
